### ISSUE TITLE
part 5. MongoDB not connected

### ISSUE THREAD

**Issue by L00ka5z78** [NathansStuff/kickstarterCloneYoutubePart5#1]
After following part 4 and 5 an fixing all errors I'm facing a small problem. First of all can not connect to the server. I get this error:

backend\server.ts:11
Colors.colors('', '');
       ^
TypeError: Cannot read properties of undefined (reading 'colors')

After commenting this Colors.colors('', '') section I am connected to server, but NOT to database.
Im wondering if it is because this colors package..

What I tried to do: 

1. Do some changes in db.ts like removing colors in those console.logs:
         console.log('MongoDB connected'.blue.underline.bold);
         console.log(err.message.red.underline.bold);
2. Check whole code for typos.
3. Checked whole code for potential sources of problems
4. Search sollutions in the internet for some tips...

I didnt find sollution for this issue, and will try to fix it on my own, but im running out of ideas..
Maybe somebody faced a similar problem and can help here.

**Comment by NathansStuff** [comment]
I've had a look at your repo, the colors issue is unrelated to the connection to the DB issue.

Colors: 
change import Colors from 'colors.ts' to: 
import * as Colors from 'colors.ts';

DB:
You are defining the function db in this line:
export const db = async (): Promise<void> => {
    await connectDB();
};

But you are never calling that function. Add this line afterwards:
void db();

That solved your issues on my local, though I also had to fiddle with the tsconfig.json and package.json to get it running properly. In case you have the same issues, I ended up adding: 
tsconfig.json:
     "target": "es2017",
      "module": "Commonjs",

package.json:
    "compilerOptions": {
        "module": "CommonJS"
    },

On top of the existing things. Hope it helps!

**Comment by L00ka5z78** [comment]
Nope, it didnt help. Now throws this: 
MONGO_URL is not defined in the env file! 
and this is console.log from db.ts. 
.env file is ok. I changed the code as you mentioned in the post above, and changed tsconfig.json and package.json
Actually it doesnt matter if this lines are in those json files, it is the same.
I will try to mess around with code to get it connected.

**Comment by NathansStuff** [comment]
So that's a positive step forward in the debugging process. The error message changed. 

In db.ts,   if (MONGO_URI === '' || MONGO_URI === null) {
        console.log(
            'MONGO_URL is not defined in the env file!'.red.underline.bold
        );
        process.exit(1);
    }
    
 That is throwing the error. 
 
 In config.ts, export const MONGO_URI = process.env.MONGO_URI ?? null;



So you have to make sure that the env is correct.

If you want to debug this, I'd suggest going to server.ts, after the imports, before any code and console.log(MONGO_URI) and update the import like such: import { MONGO_URI, PORT } from './utils/config';

What gets console logged? Does your mongo connection url string get console logged out? 

But that specific, new error is 100% to do with the .env file and/or the variables names within the env file.

Edit: Alternatively, see if you change config.ts to export const MONGO_URI = mongodb+srv://etcetcetc (a real connection string). And DONT store it in the env; directly hardcode it. Do you get the same error? If you don't, then the .env file, variable name or env config is setup wrong.

**Comment by L00ka5z78** [comment]
I tried to fix it. console.log shows null, but not url string. After following your alterntive way it shows something different, but im not sure it is a 'positive' kind of error or it just need more debugging. 
 
So it looks like that something is wrong as you suppose with variables names in the .env file. But cant figure it out what would be.  Followed your tips, few times in a row including changes in package.json and tsconfig. Still no sucess.
I uploaded picture how  errors looks like. 


![2022-11-16](https://user-images.githubusercontent.com/110019733/202117221-8da0361f-701b-4957-84dc-4b5f5a95ffc0.png)

**Comment by NathansStuff** [comment]
The screenshots help a lot. That is a positive error because it confirms that the problem has changed. Whenever the problem changes, this is new knowledge and/or you have solved another layer of the problem. In this case, it confirms for me that the .env is not being read properly.

I'm taking a guess that you didn't save the config.ts file with the commented out line before running the program hence the errors it has. When exporting it as a string (in quotes, below), please also comment out the later line where it is equal to process.env

Just to confirm, because it looks like it is not in the screenshots, but when you put export const MONGO_URI = mongo... etc in the config.ts file, you are putting it inside quotes? export const MONGO_URI = 'mongo...'

Is the same thing occuring with the other variables? If you console.log PORT or NODE_ENV, is it the default 5000 or the value (eg, 3000) in your .env file?

Where is the .env file located? At the same level as the .env.sample yes?

You have a few scripts in your package.json. Which one are you running? start:dev?

To reiterate: 
The colors problem and mongo connection not being called is solved.
New problem is that your .env is not configured correctly.

Please try by both commenting out the MONGO_URI = process.env.MONGO_URI line and by adding string quotes around the new MONGOU_URI = 'string' line as in the screenshot. 
![Capture](https://user-images.githubusercontent.com/63134709/202148102-f35f0d68-cb27-4a96-b02b-3611594f3846.PNG)

Feel free to send me a DM if you are still having trouble, because there are a lot of moving parts to this it might take a while to get you sorted via messages.

**Comment by NathansStuff** [comment]
Also, I have to ask, are you familiar / have done similar projects before with with Javascript / Node / Express and are following along to learn how to do the same with typescript or is this your first exposure to this?

**Comment by L00ka5z78** [comment]
Problem fixed. With some console.logging and actually messing around in .env file. Changed totally everything and copied mongo string from mongoCompass changed single quotes to double quotes and suddenly it worked. 
So, thanks for your help and time. Now Im moving forward and studied the next part. Very good content, Im got some troubles with Postman and generating tokens, Cant figure out how tou use them, but i remember it was in one of your previous videos.

Im familar with JS, Node, express, and databases (mysql2, mongo) Wrote some projects, some of them on my own, some with tutorials. Now im rewriting my old JS projects in Typescript to be more familiar.  so it is not my first  exposure to TS.
In addition Im on half way through 1 year long complete JS course (JS, node, express, db, tscript, react, nest).
